project 'AddressSuggestApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AddressSuggestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AddressSuggestApp
  pod 'DaDataAddressSuggester', :path => '../'

end
